// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/metalnet/api/v1alpha1"
	v1 "k8s.io/api/core/v1"
	types "k8s.io/apimachinery/pkg/types"
)

// FirewallRuleApplyConfiguration represents a declarative configuration of the FirewallRule type for use
// with apply.
//
// FirewallRule defines the desired state of FirewallRule
type FirewallRuleApplyConfiguration struct {
	FirewallRuleID    *types.UID                         `json:"firewallRuleID,omitempty"`
	Direction         *apiv1alpha1.FirewallRuleDirection `json:"direction,omitempty"`
	Action            *apiv1alpha1.FirewallRuleAction    `json:"action,omitempty"`
	Priority          *int32                             `json:"priority,omitempty"`
	IpFamily          *v1.IPFamily                       `json:"ipFamily,omitempty"`
	SourcePrefix      *apiv1alpha1.IPPrefix              `json:"sourcePrefix,omitempty"`
	DestinationPrefix *apiv1alpha1.IPPrefix              `json:"destinationPrefix,omitempty"`
	ProtocolMatch     *ProtocolMatchApplyConfiguration   `json:"protocolMatch,omitempty"`
}

// FirewallRuleApplyConfiguration constructs a declarative configuration of the FirewallRule type for use with
// apply.
func FirewallRule() *FirewallRuleApplyConfiguration {
	return &FirewallRuleApplyConfiguration{}
}

// WithFirewallRuleID sets the FirewallRuleID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FirewallRuleID field is set to the value of the last call.
func (b *FirewallRuleApplyConfiguration) WithFirewallRuleID(value types.UID) *FirewallRuleApplyConfiguration {
	b.FirewallRuleID = &value
	return b
}

// WithDirection sets the Direction field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Direction field is set to the value of the last call.
func (b *FirewallRuleApplyConfiguration) WithDirection(value apiv1alpha1.FirewallRuleDirection) *FirewallRuleApplyConfiguration {
	b.Direction = &value
	return b
}

// WithAction sets the Action field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Action field is set to the value of the last call.
func (b *FirewallRuleApplyConfiguration) WithAction(value apiv1alpha1.FirewallRuleAction) *FirewallRuleApplyConfiguration {
	b.Action = &value
	return b
}

// WithPriority sets the Priority field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Priority field is set to the value of the last call.
func (b *FirewallRuleApplyConfiguration) WithPriority(value int32) *FirewallRuleApplyConfiguration {
	b.Priority = &value
	return b
}

// WithIpFamily sets the IpFamily field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IpFamily field is set to the value of the last call.
func (b *FirewallRuleApplyConfiguration) WithIpFamily(value v1.IPFamily) *FirewallRuleApplyConfiguration {
	b.IpFamily = &value
	return b
}

// WithSourcePrefix sets the SourcePrefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SourcePrefix field is set to the value of the last call.
func (b *FirewallRuleApplyConfiguration) WithSourcePrefix(value apiv1alpha1.IPPrefix) *FirewallRuleApplyConfiguration {
	b.SourcePrefix = &value
	return b
}

// WithDestinationPrefix sets the DestinationPrefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DestinationPrefix field is set to the value of the last call.
func (b *FirewallRuleApplyConfiguration) WithDestinationPrefix(value apiv1alpha1.IPPrefix) *FirewallRuleApplyConfiguration {
	b.DestinationPrefix = &value
	return b
}

// WithProtocolMatch sets the ProtocolMatch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProtocolMatch field is set to the value of the last call.
func (b *FirewallRuleApplyConfiguration) WithProtocolMatch(value *ProtocolMatchApplyConfiguration) *FirewallRuleApplyConfiguration {
	b.ProtocolMatch = value
	return b
}
