// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ICMPMatchApplyConfiguration represents a declarative configuration of the ICMPMatch type for use
// with apply.
type ICMPMatchApplyConfiguration struct {
	IcmpType *int32 `json:"icmpType,omitempty"`
	IcmpCode *int32 `json:"icmpCode,omitempty"`
}

// ICMPMatchApplyConfiguration constructs a declarative configuration of the ICMPMatch type for use with
// apply.
func ICMPMatch() *ICMPMatchApplyConfiguration {
	return &ICMPMatchApplyConfiguration{}
}

// WithIcmpType sets the IcmpType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IcmpType field is set to the value of the last call.
func (b *ICMPMatchApplyConfiguration) WithIcmpType(value int32) *ICMPMatchApplyConfiguration {
	b.IcmpType = &value
	return b
}

// WithIcmpCode sets the IcmpCode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IcmpCode field is set to the value of the last call.
func (b *ICMPMatchApplyConfiguration) WithIcmpCode(value int32) *ICMPMatchApplyConfiguration {
	b.IcmpCode = &value
	return b
}
