// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// LBPortApplyConfiguration represents a declarative configuration of the LBPort type for use
// with apply.
//
// LBPort consists of port and protocol
type LBPortApplyConfiguration struct {
	Protocol *string `json:"protocol,omitempty"`
	Port     *int32  `json:"port,omitempty"`
}

// LBPortApplyConfiguration constructs a declarative configuration of the LBPort type for use with
// apply.
func LBPort() *LBPortApplyConfiguration {
	return &LBPortApplyConfiguration{}
}

// WithProtocol sets the Protocol field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Protocol field is set to the value of the last call.
func (b *LBPortApplyConfiguration) WithProtocol(value string) *LBPortApplyConfiguration {
	b.Protocol = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *LBPortApplyConfiguration) WithPort(value int32) *LBPortApplyConfiguration {
	b.Port = &value
	return b
}
