// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/metalnet/api/v1alpha1"
)

// LoadBalancerStatusApplyConfiguration represents a declarative configuration of the LoadBalancerStatus type for use
// with apply.
//
// LoadBalancerStatus defines the observed state of LoadBalancer
type LoadBalancerStatusApplyConfiguration struct {
	// State is the LoadBalancerState of the LoadBalancer.
	State *apiv1alpha1.LoadBalancerState `json:"state,omitempty"`
}

// LoadBalancerStatusApplyConfiguration constructs a declarative configuration of the LoadBalancerStatus type for use with
// apply.
func LoadBalancerStatus() *LoadBalancerStatusApplyConfiguration {
	return &LoadBalancerStatusApplyConfiguration{}
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *LoadBalancerStatusApplyConfiguration) WithState(value apiv1alpha1.LoadBalancerState) *LoadBalancerStatusApplyConfiguration {
	b.State = &value
	return b
}
