// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/metalnet/api/v1alpha1"
	v1 "k8s.io/api/core/v1"
)

// LoadBalancerSpecApplyConfiguration represents a declarative configuration of the LoadBalancerSpec type for use
// with apply.
//
// LoadBalancerSpec defines the desired state of LoadBalancer
type LoadBalancerSpecApplyConfiguration struct {
	// NetworkRef is the Network this LoadBalancer is connected to
	NetworkRef *v1.LocalObjectReference `json:"networkRef,omitempty"`
	// Type defines whether the loadbalancer is using an internal or public ip
	LBtype *apiv1alpha1.LoadBalancerType `json:"type,omitempty"`
	// IPFamily defines which IPFamily this LoadBalancer is supporting
	IPFamily *v1.IPFamily `json:"ipFamily,omitempty"`
	// IP is the provided IP which should be loadbalanced by this LoadBalancer
	IP *apiv1alpha1.IP `json:"ip,omitempty"`
	// Ports are the provided ports
	Ports []LBPortApplyConfiguration `json:"ports,omitempty"`
	// NodeName is the name of the node on which the LoadBalancer should be created.
	NodeName *string `json:"nodeName,omitempty"`
}

// LoadBalancerSpecApplyConfiguration constructs a declarative configuration of the LoadBalancerSpec type for use with
// apply.
func LoadBalancerSpec() *LoadBalancerSpecApplyConfiguration {
	return &LoadBalancerSpecApplyConfiguration{}
}

// WithNetworkRef sets the NetworkRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NetworkRef field is set to the value of the last call.
func (b *LoadBalancerSpecApplyConfiguration) WithNetworkRef(value v1.LocalObjectReference) *LoadBalancerSpecApplyConfiguration {
	b.NetworkRef = &value
	return b
}

// WithLBtype sets the LBtype field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LBtype field is set to the value of the last call.
func (b *LoadBalancerSpecApplyConfiguration) WithLBtype(value apiv1alpha1.LoadBalancerType) *LoadBalancerSpecApplyConfiguration {
	b.LBtype = &value
	return b
}

// WithIPFamily sets the IPFamily field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IPFamily field is set to the value of the last call.
func (b *LoadBalancerSpecApplyConfiguration) WithIPFamily(value v1.IPFamily) *LoadBalancerSpecApplyConfiguration {
	b.IPFamily = &value
	return b
}

// WithIP sets the IP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IP field is set to the value of the last call.
func (b *LoadBalancerSpecApplyConfiguration) WithIP(value apiv1alpha1.IP) *LoadBalancerSpecApplyConfiguration {
	b.IP = &value
	return b
}

// WithPorts adds the given value to the Ports field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Ports field.
func (b *LoadBalancerSpecApplyConfiguration) WithPorts(values ...*LBPortApplyConfiguration) *LoadBalancerSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPorts")
		}
		b.Ports = append(b.Ports, *values[i])
	}
	return b
}

// WithNodeName sets the NodeName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeName field is set to the value of the last call.
func (b *LoadBalancerSpecApplyConfiguration) WithNodeName(value string) *LoadBalancerSpecApplyConfiguration {
	b.NodeName = &value
	return b
}
