// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// MeteringParametersApplyConfiguration represents a declarative configuration of the MeteringParameters type for use
// with apply.
type MeteringParametersApplyConfiguration struct {
	TotalRate  *uint64 `json:"totalRate,omitempty"`
	PublicRate *uint64 `json:"publicRate,omitempty"`
}

// MeteringParametersApplyConfiguration constructs a declarative configuration of the MeteringParameters type for use with
// apply.
func MeteringParameters() *MeteringParametersApplyConfiguration {
	return &MeteringParametersApplyConfiguration{}
}

// WithTotalRate sets the TotalRate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TotalRate field is set to the value of the last call.
func (b *MeteringParametersApplyConfiguration) WithTotalRate(value uint64) *MeteringParametersApplyConfiguration {
	b.TotalRate = &value
	return b
}

// WithPublicRate sets the PublicRate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PublicRate field is set to the value of the last call.
func (b *MeteringParametersApplyConfiguration) WithPublicRate(value uint64) *MeteringParametersApplyConfiguration {
	b.PublicRate = &value
	return b
}
