// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/metalnet/api/v1alpha1"
)

// NATDetailsApplyConfiguration represents a declarative configuration of the NATDetails type for use
// with apply.
//
// LBPort consists of port and protocol
type NATDetailsApplyConfiguration struct {
	IP      *apiv1alpha1.IP `json:"ip,omitempty"`
	Port    *int32          `json:"port,omitempty"`
	EndPort *int32          `json:"endPort,omitempty"`
}

// NATDetailsApplyConfiguration constructs a declarative configuration of the NATDetails type for use with
// apply.
func NATDetails() *NATDetailsApplyConfiguration {
	return &NATDetailsApplyConfiguration{}
}

// WithIP sets the IP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IP field is set to the value of the last call.
func (b *NATDetailsApplyConfiguration) WithIP(value apiv1alpha1.IP) *NATDetailsApplyConfiguration {
	b.IP = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *NATDetailsApplyConfiguration) WithPort(value int32) *NATDetailsApplyConfiguration {
	b.Port = &value
	return b
}

// WithEndPort sets the EndPort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EndPort field is set to the value of the last call.
func (b *NATDetailsApplyConfiguration) WithEndPort(value int32) *NATDetailsApplyConfiguration {
	b.EndPort = &value
	return b
}
