// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// NetworkSpecApplyConfiguration represents a declarative configuration of the NetworkSpec type for use
// with apply.
//
// EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
// NOTE: json tags are required.  Any new fields you add must have json tags for the fields to be serialized.
// NetworkSpec defines the desired state of Network
type NetworkSpecApplyConfiguration struct {
	// ID is the unique identifier of the Network
	ID *int32 `json:"id,omitempty"`
	// PeeredIDs are the IDs of networks to peer with.
	PeeredIDs []int32 `json:"peeredIDs,omitempty"`
	// PeeredPrefixes are the allowed CIDRs of the peered networks.
	PeeredPrefixes []PeeredPrefixApplyConfiguration `json:"peeredPrefixes,omitempty"`
}

// NetworkSpecApplyConfiguration constructs a declarative configuration of the NetworkSpec type for use with
// apply.
func NetworkSpec() *NetworkSpecApplyConfiguration {
	return &NetworkSpecApplyConfiguration{}
}

// WithID sets the ID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ID field is set to the value of the last call.
func (b *NetworkSpecApplyConfiguration) WithID(value int32) *NetworkSpecApplyConfiguration {
	b.ID = &value
	return b
}

// WithPeeredIDs adds the given value to the PeeredIDs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PeeredIDs field.
func (b *NetworkSpecApplyConfiguration) WithPeeredIDs(values ...int32) *NetworkSpecApplyConfiguration {
	for i := range values {
		b.PeeredIDs = append(b.PeeredIDs, values[i])
	}
	return b
}

// WithPeeredPrefixes adds the given value to the PeeredPrefixes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PeeredPrefixes field.
func (b *NetworkSpecApplyConfiguration) WithPeeredPrefixes(values ...*PeeredPrefixApplyConfiguration) *NetworkSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPeeredPrefixes")
		}
		b.PeeredPrefixes = append(b.PeeredPrefixes, *values[i])
	}
	return b
}
