// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/metalnet/api/v1alpha1"
)

// NetworkInterfaceStatusApplyConfiguration represents a declarative configuration of the NetworkInterfaceStatus type for use
// with apply.
//
// NetworkInterfaceStatus defines the observed state of NetworkInterface
type NetworkInterfaceStatusApplyConfiguration struct {
	PCIAddress *PCIAddressApplyConfiguration `json:"pciAddress,omitempty"`
	TAPDevice  *TAPDeviceApplyConfiguration  `json:"tapDevice,omitempty"`
	// VirtualIP is any virtual ip assigned to the NetworkInterface.
	VirtualIP *apiv1alpha1.IP `json:"virtualIP,omitempty"`
	// NatIP is detailed information about the NAT on this interface
	NatIP *NATDetailsApplyConfiguration `json:"natIP,omitempty"`
	// Prefixes are the Prefixes reserved for this NetworkInterface
	Prefixes []apiv1alpha1.IPPrefix `json:"prefixes,omitempty"`
	// LoadBalancerTargets are the Targets reserved for this NetworkInterface
	LoadBalancerTargets []apiv1alpha1.IPPrefix `json:"loadBalancerTargets,omitempty"`
	// State is the NetworkInterfaceState of the NetworkInterface.
	State *apiv1alpha1.NetworkInterfaceState `json:"state,omitempty"`
}

// NetworkInterfaceStatusApplyConfiguration constructs a declarative configuration of the NetworkInterfaceStatus type for use with
// apply.
func NetworkInterfaceStatus() *NetworkInterfaceStatusApplyConfiguration {
	return &NetworkInterfaceStatusApplyConfiguration{}
}

// WithPCIAddress sets the PCIAddress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PCIAddress field is set to the value of the last call.
func (b *NetworkInterfaceStatusApplyConfiguration) WithPCIAddress(value *PCIAddressApplyConfiguration) *NetworkInterfaceStatusApplyConfiguration {
	b.PCIAddress = value
	return b
}

// WithTAPDevice sets the TAPDevice field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TAPDevice field is set to the value of the last call.
func (b *NetworkInterfaceStatusApplyConfiguration) WithTAPDevice(value *TAPDeviceApplyConfiguration) *NetworkInterfaceStatusApplyConfiguration {
	b.TAPDevice = value
	return b
}

// WithVirtualIP sets the VirtualIP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VirtualIP field is set to the value of the last call.
func (b *NetworkInterfaceStatusApplyConfiguration) WithVirtualIP(value apiv1alpha1.IP) *NetworkInterfaceStatusApplyConfiguration {
	b.VirtualIP = &value
	return b
}

// WithNatIP sets the NatIP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NatIP field is set to the value of the last call.
func (b *NetworkInterfaceStatusApplyConfiguration) WithNatIP(value *NATDetailsApplyConfiguration) *NetworkInterfaceStatusApplyConfiguration {
	b.NatIP = value
	return b
}

// WithPrefixes adds the given value to the Prefixes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Prefixes field.
func (b *NetworkInterfaceStatusApplyConfiguration) WithPrefixes(values ...apiv1alpha1.IPPrefix) *NetworkInterfaceStatusApplyConfiguration {
	for i := range values {
		b.Prefixes = append(b.Prefixes, values[i])
	}
	return b
}

// WithLoadBalancerTargets adds the given value to the LoadBalancerTargets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the LoadBalancerTargets field.
func (b *NetworkInterfaceStatusApplyConfiguration) WithLoadBalancerTargets(values ...apiv1alpha1.IPPrefix) *NetworkInterfaceStatusApplyConfiguration {
	for i := range values {
		b.LoadBalancerTargets = append(b.LoadBalancerTargets, values[i])
	}
	return b
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *NetworkInterfaceStatusApplyConfiguration) WithState(value apiv1alpha1.NetworkInterfaceState) *NetworkInterfaceStatusApplyConfiguration {
	b.State = &value
	return b
}
