// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/metalnet/api/v1alpha1"
	v1 "k8s.io/api/core/v1"
)

// NetworkInterfaceSpecApplyConfiguration represents a declarative configuration of the NetworkInterfaceSpec type for use
// with apply.
//
// NetworkInterfaceSpec defines the desired state of NetworkInterface
type NetworkInterfaceSpecApplyConfiguration struct {
	// NetworkRef is the Network this NetworkInterface is connected to
	NetworkRef *v1.LocalObjectReference `json:"networkRef,omitempty"`
	// IPFamilies defines which IPFamilies this NetworkInterface is supporting
	// Only one IP supported at the moment.
	IPFamilies []v1.IPFamily `json:"ipFamilies,omitempty"`
	// IPs are the provided IPs or EphemeralIPs which should be assigned to this NetworkInterface
	// Only one IP supported at the moment.
	IPs []apiv1alpha1.IP `json:"ips,omitempty"`
	// Virtual IP
	VirtualIP *apiv1alpha1.IP `json:"virtualIP,omitempty"`
	// Prefixes are the provided Prefix
	Prefixes []apiv1alpha1.IPPrefix `json:"prefixes,omitempty"`
	// Loadbalancer Targets are the provided Prefix
	LoadBalancerTargets []apiv1alpha1.IPPrefix `json:"loadBalancerTargets,omitempty"`
	// NATInfo is detailed information about the NAT on this interface
	NAT *NATDetailsApplyConfiguration `json:"nat,omitempty"`
	// NodeName is the name of the node on which the interface should be created.
	NodeName *string `json:"nodeName,omitempty"`
	// FirewallRules are the firewall rules to be applied to this interface.
	FirewallRules []FirewallRuleApplyConfiguration `json:"firewallRules,omitempty"`
	// MeteringRate are the metering parameters to be applied to this interface.
	MeteringRate *MeteringParametersApplyConfiguration `json:"meteringRate,omitempty"`
	// Hostname is the hostname which should be announced by the network interface.
	Hostname *string `json:"hostname,omitempty"`
}

// NetworkInterfaceSpecApplyConfiguration constructs a declarative configuration of the NetworkInterfaceSpec type for use with
// apply.
func NetworkInterfaceSpec() *NetworkInterfaceSpecApplyConfiguration {
	return &NetworkInterfaceSpecApplyConfiguration{}
}

// WithNetworkRef sets the NetworkRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NetworkRef field is set to the value of the last call.
func (b *NetworkInterfaceSpecApplyConfiguration) WithNetworkRef(value v1.LocalObjectReference) *NetworkInterfaceSpecApplyConfiguration {
	b.NetworkRef = &value
	return b
}

// WithIPFamilies adds the given value to the IPFamilies field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the IPFamilies field.
func (b *NetworkInterfaceSpecApplyConfiguration) WithIPFamilies(values ...v1.IPFamily) *NetworkInterfaceSpecApplyConfiguration {
	for i := range values {
		b.IPFamilies = append(b.IPFamilies, values[i])
	}
	return b
}

// WithIPs adds the given value to the IPs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the IPs field.
func (b *NetworkInterfaceSpecApplyConfiguration) WithIPs(values ...apiv1alpha1.IP) *NetworkInterfaceSpecApplyConfiguration {
	for i := range values {
		b.IPs = append(b.IPs, values[i])
	}
	return b
}

// WithVirtualIP sets the VirtualIP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VirtualIP field is set to the value of the last call.
func (b *NetworkInterfaceSpecApplyConfiguration) WithVirtualIP(value apiv1alpha1.IP) *NetworkInterfaceSpecApplyConfiguration {
	b.VirtualIP = &value
	return b
}

// WithPrefixes adds the given value to the Prefixes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Prefixes field.
func (b *NetworkInterfaceSpecApplyConfiguration) WithPrefixes(values ...apiv1alpha1.IPPrefix) *NetworkInterfaceSpecApplyConfiguration {
	for i := range values {
		b.Prefixes = append(b.Prefixes, values[i])
	}
	return b
}

// WithLoadBalancerTargets adds the given value to the LoadBalancerTargets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the LoadBalancerTargets field.
func (b *NetworkInterfaceSpecApplyConfiguration) WithLoadBalancerTargets(values ...apiv1alpha1.IPPrefix) *NetworkInterfaceSpecApplyConfiguration {
	for i := range values {
		b.LoadBalancerTargets = append(b.LoadBalancerTargets, values[i])
	}
	return b
}

// WithNAT sets the NAT field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NAT field is set to the value of the last call.
func (b *NetworkInterfaceSpecApplyConfiguration) WithNAT(value *NATDetailsApplyConfiguration) *NetworkInterfaceSpecApplyConfiguration {
	b.NAT = value
	return b
}

// WithNodeName sets the NodeName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeName field is set to the value of the last call.
func (b *NetworkInterfaceSpecApplyConfiguration) WithNodeName(value string) *NetworkInterfaceSpecApplyConfiguration {
	b.NodeName = &value
	return b
}

// WithFirewallRules adds the given value to the FirewallRules field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the FirewallRules field.
func (b *NetworkInterfaceSpecApplyConfiguration) WithFirewallRules(values ...*FirewallRuleApplyConfiguration) *NetworkInterfaceSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithFirewallRules")
		}
		b.FirewallRules = append(b.FirewallRules, *values[i])
	}
	return b
}

// WithMeteringRate sets the MeteringRate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MeteringRate field is set to the value of the last call.
func (b *NetworkInterfaceSpecApplyConfiguration) WithMeteringRate(value *MeteringParametersApplyConfiguration) *NetworkInterfaceSpecApplyConfiguration {
	b.MeteringRate = value
	return b
}

// WithHostname sets the Hostname field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Hostname field is set to the value of the last call.
func (b *NetworkInterfaceSpecApplyConfiguration) WithHostname(value string) *NetworkInterfaceSpecApplyConfiguration {
	b.Hostname = &value
	return b
}
