// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/metalnet/api/v1alpha1"
)

// PeeredPrefixApplyConfiguration represents a declarative configuration of the PeeredPrefix type for use
// with apply.
//
// PeeredPrefix contains information of the peered networks and their allowed CIDRs.
type PeeredPrefixApplyConfiguration struct {
	ID       *int32                 `json:"id,omitempty"`
	Prefixes []apiv1alpha1.IPPrefix `json:"prefixes,omitempty"`
}

// PeeredPrefixApplyConfiguration constructs a declarative configuration of the PeeredPrefix type for use with
// apply.
func PeeredPrefix() *PeeredPrefixApplyConfiguration {
	return &PeeredPrefixApplyConfiguration{}
}

// WithID sets the ID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ID field is set to the value of the last call.
func (b *PeeredPrefixApplyConfiguration) WithID(value int32) *PeeredPrefixApplyConfiguration {
	b.ID = &value
	return b
}

// WithPrefixes adds the given value to the Prefixes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Prefixes field.
func (b *PeeredPrefixApplyConfiguration) WithPrefixes(values ...apiv1alpha1.IPPrefix) *PeeredPrefixApplyConfiguration {
	for i := range values {
		b.Prefixes = append(b.Prefixes, values[i])
	}
	return b
}
