// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// PortMatchApplyConfiguration represents a declarative configuration of the PortMatch type for use
// with apply.
type PortMatchApplyConfiguration struct {
	SrcPort    *int32 `json:"srcPort,omitempty"`
	EndSrcPort *int32 `json:"endSrcPort,omitempty"`
	DstPort    *int32 `json:"dstPort,omitempty"`
	EndDstPort *int32 `json:"endDstPort,omitempty"`
}

// PortMatchApplyConfiguration constructs a declarative configuration of the PortMatch type for use with
// apply.
func PortMatch() *PortMatchApplyConfiguration {
	return &PortMatchApplyConfiguration{}
}

// WithSrcPort sets the SrcPort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SrcPort field is set to the value of the last call.
func (b *PortMatchApplyConfiguration) WithSrcPort(value int32) *PortMatchApplyConfiguration {
	b.SrcPort = &value
	return b
}

// WithEndSrcPort sets the EndSrcPort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EndSrcPort field is set to the value of the last call.
func (b *PortMatchApplyConfiguration) WithEndSrcPort(value int32) *PortMatchApplyConfiguration {
	b.EndSrcPort = &value
	return b
}

// WithDstPort sets the DstPort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DstPort field is set to the value of the last call.
func (b *PortMatchApplyConfiguration) WithDstPort(value int32) *PortMatchApplyConfiguration {
	b.DstPort = &value
	return b
}

// WithEndDstPort sets the EndDstPort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EndDstPort field is set to the value of the last call.
func (b *PortMatchApplyConfiguration) WithEndDstPort(value int32) *PortMatchApplyConfiguration {
	b.EndDstPort = &value
	return b
}
