// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/metalnet/api/v1alpha1"
)

// ProtocolMatchApplyConfiguration represents a declarative configuration of the ProtocolMatch type for use
// with apply.
type ProtocolMatchApplyConfiguration struct {
	ProtocolType *apiv1alpha1.ProtocolType    `json:"protocolType,omitempty"`
	ICMP         *ICMPMatchApplyConfiguration `json:"icmp,omitempty"`
	PortRange    *PortMatchApplyConfiguration `json:"portRange,omitempty"`
}

// ProtocolMatchApplyConfiguration constructs a declarative configuration of the ProtocolMatch type for use with
// apply.
func ProtocolMatch() *ProtocolMatchApplyConfiguration {
	return &ProtocolMatchApplyConfiguration{}
}

// WithProtocolType sets the ProtocolType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProtocolType field is set to the value of the last call.
func (b *ProtocolMatchApplyConfiguration) WithProtocolType(value apiv1alpha1.ProtocolType) *ProtocolMatchApplyConfiguration {
	b.ProtocolType = &value
	return b
}

// WithICMP sets the ICMP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ICMP field is set to the value of the last call.
func (b *ProtocolMatchApplyConfiguration) WithICMP(value *ICMPMatchApplyConfiguration) *ProtocolMatchApplyConfiguration {
	b.ICMP = value
	return b
}

// WithPortRange sets the PortRange field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PortRange field is set to the value of the last call.
func (b *ProtocolMatchApplyConfiguration) WithPortRange(value *PortMatchApplyConfiguration) *ProtocolMatchApplyConfiguration {
	b.PortRange = value
	return b
}
