run:
  modules-download-mode: vendor
  timeout: 3m

linters:
  enable:
    - revive
    - ineffassign
    - misspell
    - goimports
  disable:
    -typecheck

severity:
  default-severity: error

linters-settings:
  misspell:
    ignore-words:
      - strat
  revive:
    severity: error
    rules:
      - name: exported
      - name: if-return
        disabled: true
