apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - command:
        - /manager
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        args:
        - --node-name=$(NODE_NAME)
        image: controller:latest
        name: manager
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /sys
          name: sysfs
        - mountPath: /usr/share/misc/
          name: pciids
        - mountPath: /var/lib/metalnet
          name: metalnet
      volumes:
      - hostPath:
          path: /sys
          type: ""
        name: sysfs
      - hostPath:
          path: /usr/share/misc/
          type: ""
        name: pciids
      - hostPath:
          path: /var/lib/metalnet
          type: DirectoryOrCreate
        name: metalnet
      hostNetwork: true
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
