apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - command:
        - /manager
        args:
        - --dpservice-address=127.0.0.1:1337
        - --metalbondserver-address=2a10:afc0:e01f:f4::2
        - --metalbondserver-port=4711
        image: localhost:5000/controller:latest
        name: manager
        resources:
          requests:
            cpu: 1000m
            memory: 200Mi
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /sys
          name: sysfs
        - mountPath: /usr/share/misc/
          name: pciids
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      volumes:
      - hostPath:
          path: /sys
          type: ""
        name: sysfs
      - hostPath:
          path: /usr/share/misc/
          type: ""
        name: pciids
      hostNetwork: true
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
