// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package applyconfiguration

import (
	v1alpha1 "github.com/ironcore-dev/metalnet/api/v1alpha1"
	apiv1alpha1 "github.com/ironcore-dev/metalnet/api/v1alpha1/applyconfiguration/api/v1alpha1"
	internal "github.com/ironcore-dev/metalnet/api/v1alpha1/applyconfiguration/internal"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=networking.metalnet.ironcore.dev, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithKind("FirewallRule"):
		return &apiv1alpha1.FirewallRuleApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ICMPMatch"):
		return &apiv1alpha1.ICMPMatchApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("MeteringParameters"):
		return &apiv1alpha1.MeteringParametersApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NATDetails"):
		return &apiv1alpha1.NATDetailsApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NetworkInterface"):
		return &apiv1alpha1.NetworkInterfaceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NetworkInterfaceSpec"):
		return &apiv1alpha1.NetworkInterfaceSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NetworkInterfaceStatus"):
		return &apiv1alpha1.NetworkInterfaceStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("PCIAddress"):
		return &apiv1alpha1.PCIAddressApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("PortMatch"):
		return &apiv1alpha1.PortMatchApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ProtocolMatch"):
		return &apiv1alpha1.ProtocolMatchApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("TAPDevice"):
		return &apiv1alpha1.TAPDeviceApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
