# permissions for end users to edit loadbalancers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: loadbalancer-editor-role
rules:
- apiGroups:
  - networking.metalnet.onmetal.de
  resources:
  - loadbalancers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.metalnet.onmetal.de
  resources:
  - loadbalancers/status
  verbs:
  - get
