# permissions for end users to edit networkfunctions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: networkfunction-editor-role
rules:
- apiGroups:
  - networking.metalnet.onmetal.de
  resources:
  - networkfunctions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.metalnet.onmetal.de
  resources:
  - networkfunctions/status
  verbs:
  - get
