# permissions for end users to view networkfunctions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: networkfunction-viewer-role
rules:
- apiGroups:
  - networking.metalnet.onmetal.de
  resources:
  - networkfunctions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.metalnet.onmetal.de
  resources:
  - networkfunctions/status
  verbs:
  - get
