---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - networking.metalnet.onmetal.de
  resources:
  - loadbalancers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.metalnet.onmetal.de
  resources:
  - loadbalancers/finalizers
  verbs:
  - update
- apiGroups:
  - networking.metalnet.onmetal.de
  resources:
  - loadbalancers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.metalnet.onmetal.de
  resources:
  - networkinterfaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.metalnet.onmetal.de
  resources:
  - networkinterfaces/finalizers
  verbs:
  - update
- apiGroups:
  - networking.metalnet.onmetal.de
  resources:
  - networkinterfaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.metalnet.onmetal.de
  resources:
  - networks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.metalnet.onmetal.de
  resources:
  - networks/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - networking.metalnet.onmetal.de
  resources:
  - networks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
    - ""
  resources:
    - pods
  verbs:
    - get
    - list
    - watch
