---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - networking.metalnet.onmetal.de
  resources:
  - networkfunctions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.metalnet.onmetal.de
  resources:
  - networkfunctions/finalizers
  verbs:
  - update
- apiGroups:
  - networking.metalnet.onmetal.de
  resources:
  - networkfunctions/status
  verbs:
  - get
  - patch
  - update
