---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - networking.metalnet.ironcore.dev
  resources:
  - loadbalancers
  - networkinterfaces
  - networks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.metalnet.ironcore.dev
  resources:
  - loadbalancers/finalizers
  - networkinterfaces/finalizers
  verbs:
  - update
- apiGroups:
  - networking.metalnet.ironcore.dev
  resources:
  - loadbalancers/status
  - networkinterfaces/status
  - networks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.metalnet.ironcore.dev
  resources:
  - networks/finalizers
  verbs:
  - patch
  - update
