# permissions for end users to edit virtualips.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualip-editor-role
rules:
- apiGroups:
  - networking.metalnet.onmetal.de
  resources:
  - virtualips
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.metalnet.onmetal.de
  resources:
  - virtualips/status
  verbs:
  - get
