apiVersion: networking.metalnet.onmetal.de/v1alpha1
kind: VirtualIP
metadata:
  name: virtualip-sample
spec:
  type: Public
  ipFamily: IPv4
  ip: 194.11.242.11
  targetRef: 
    name: networkinterface-sample
