apiVersion: networking.metalnet.onmetal.de/v1alpha1
kind: AliasPrefix
metadata:
  name: aliasprefix-sample
spec:
  networkRef:
    name: network-sample
  networkInterfaceSelector:
    matchLabels:
      lab: fra4-lab
  prefix:
    value: 10.1.1.0/24
