apiVersion: networking.metalnet.onmetal.de/v1alpha1
kind: NetworkInterface
metadata:
  name: networkinterface-sample
spec:
  ipFamilies:
    - "IPv4"
  ips:
    - 10.0.0.2
  virtualIP: 194.11.242.11
  nodeName: guvenc-vm
  nat:
    ip: 194.11.242.10
    port: 1024
    endPort: 1087
  loadBalancerTargets:
    - 194.11.242.110/32
  networkRef:
    name: network-sample
  firewallRules:
    -
      firewallRuleID: "fr1"
      direction: "INGRESS"
      action: "ACCEPT"
      ipFamily: "IPv4"
      sourcePrefix: "0.0.0.0/0"
      protocolMatch:
        protocolType: "TCP"
        portRange:
          srcPort: 80
          endSrcPort: 80
    -
      firewallRuleID: "fr2"
      direction: "EGRESS"
      action: "ACCEPT"
      ipFamily: "IPv4"
      protocolMatch:
        protocolType: "UDP"
        portRange:
          srcPort: 2000
          endSrcPort: 2400
