apiVersion: networking.metalnet.onmetal.de/v1alpha1
kind: NetworkInterface
metadata:
  name: networkinterface-sample
spec:
  ipFamilies:
    - "IPv4"
  ip:
    - 10.0.0.2
#  vip: 194.11.242.11
  prefix: 
    - 10.1.1.0/24
    - 10.3.3.0/24
    - 10.4.4.0/24
  nodeName: fra4-lab-dell-2
  networkRef:
    name: network-sample
