name: Pull Request Code test

on:
  push:
    branches:
      - 'feature/*'
  pull_request_target:
    types: [ assigned, opened, synchronize, reopened ]
    paths-ignore:
      - 'docs/**'
      - '**/*.md'

jobs:
  checks:
    name: run
    runs-on: [ self-hosted, dpdk ]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Download metalbond using the script
        run: ./hack/rel_download.sh -dir=build -owner=onmetal -repo=metalbond -pat=${{ secrets.BOT_PAT }}

      - name: Install metalbond
        run: sudo dpkg -i build/metalbond*.deb

      - name: Start metalbond
        run: metalbond server --listen [::1]:4711 --http [::1]:4712 --keepalive 3 &

      - name: Run dp-service
        run: docker run -it --rm --entrypoint ./dp_service.py --privileged -p1337:1337 --mount type=bind,source=/dev/hugepages,target=/dev/hugepages ghcr.io/onmetal/dp-service-tester --no-init &

      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - run: |
          mkdir -p ~/.ssh
          for key in rsa ecdsa ed25519; do
            ssh-keyscan -t $key github.com 2>/dev/null >> ~/.ssh/known_hosts
          done
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.BOT_PRIVATE_KEY }}
      - run: ./hack/setup-git-redirect.sh
      - run: make test
      - name: Delete git global config
        if: always()
        run: |
          rm ~/.gitconfig
